version: '2.1'

services:
  xaydung_w_gis:
    image: xaydung_w_gis
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js