import { APPLICATION } from './core.constant';
export const BASEMAP = {
  INDEX_HANH_CHINH: 13,
  MaHuyenTP: 'MaQuanHuyen',
  MaPhuongXa: 'MaPhuongXa',
  MaDuong: 'MaDuong'
};

export const SERVICE_PRINT =
  'https://ditagis.com/arcgis/rest/services/Utilities/PrintingTools/GPServer/Export%20Web%20Map%20Task';

export const LAYER = {
  BASE_MAP: 'basemap',
  RanhGioiQuyHoach: 'ranhgioiquyhoachLYR',
  DIEM_SU_CO: 'diemsucoLYR',
  HienTrang: 'hientrang',
  QuyHoachChiTiet: 'quyhoachchitiet',
  QuyHoachChung: 'quyhoachchung',
  QuyHoachNongThonMoi: 'quyhoachnongthonmoi',
  QuyHoachPhanKhu: 'quyhoachphankhu',
  BaoVeMoiTruong: 'htbaovemoitruongLYR',
  BeChua: 'htbechuaLYR',
  BuuCuc: 'htbuucucLYR',
  CayXanh: 'htcayxanhLYR',
  CongThoatNuoc: 'htcongthoatnuocLYR',
  CongVien: 'htcongvienLYR',
  CotDien: 'htcotdienLYR',
  CongTrinhCaoTang: 'htctrcaotangLYR',
  CongTrinhNgam: 'htctrngamLYR',
  CongTrinhXayDung: 'htctrxaydungLYR',
  DuongDayTruyenTai: 'htddtruyentaiLYR',
  DenChieuSang: 'htdenchieusangLYR',
  DenGiaoThong: 'htdengiaothongLYR',
  DongHoKhachHang: 'htdhkhLYR',
  DiemCuoiOng: 'htdiemcuoiongLYR',
  DiemNut: 'htdiemnutLYR',
  DongHoTong: 'htdonghotongYR',
  GiaoThong: 'htgiaothongLYR',
  Gieng: 'htgiengLYR',
  HoGa: 'hthogaLYR',
  HostDieuKhien: 'hthostdieukhienLYR',
  KhuVucNgap: 'htkhuvucngapLYR',
  KhuVucXuLyRacThai: 'htkhuxulyracthaiLYR',
  LuuVucThoatNuoc: 'htluuvucthoatnuocLYR',
  MiengXa: 'htmiengxaLYR',
  MoiNoiThoatNuoc: 'htmoinoithoatnuocLYR',
  NghiaTrang: 'htnghiatrangLYR',
  NguonGayONhiem: 'htnguongayonhiemLYR',
  NhaMayDien: 'htnhamaydienLYR',
  NhaMayNuoc: 'htnhamaynuocLYR',
  NutCongSuat: 'htnutcongsuatLYR',
  PhuTai: 'htphutaiLYR',
  SuDungDat: 'htsudungdatLYR',
  CapTruyenDan: 'httcaptruyendanLYR',
  DayChieuSang: 'httdaychieusangLYR',
  ThietBiDien: 'htthietbidienLYR',
  TimDuong: 'httimduongLYR',
  TramBienAp: 'httrambienapLYR',
  TramBom: 'httrambomLYR',
  TramVienThong: 'httramvienthongLYR',
  TramXuLyNuocThai: 'httramxlntLYR',
  TramTrungChuyenCTR: 'htttchuyenctrLYR',
  TuyenOngCapNuoc: 'httuyenongcapnuocLYR',
  Van: 'htvanLYR',
  ViTriLayNuoc: 'htvitrilaynuocLYR',
  ViTriDauNoiVoiTuyenOngDan: 'htvtdntuyenongdanLYR'
};
export const MAP = {
  CENTER: [106.701767, 11.132015],
  ZOOM: 10,
  SCALE: 500000
};

export const APP_LAYER = {
  [APPLICATION.ThongTinQuyHoach]: [LAYER.BASE_MAP, LAYER.QuyHoachChiTiet, LAYER.QuyHoachChung, LAYER.QuyHoachNongThonMoi, LAYER.QuyHoachPhanKhu],
  [APPLICATION.XemDuLieu]: [LAYER.BASE_MAP,
  LAYER.BaoVeMoiTruong,
  LAYER.BeChua,
  LAYER.BuuCuc,
  LAYER.CayXanh,
  LAYER.CongThoatNuoc,
  LAYER.CongVien,
  LAYER.CotDien,
  LAYER.CongTrinhCaoTang,
  LAYER.CongTrinhNgam,
  LAYER.CongTrinhXayDung,
  LAYER.DuongDayTruyenTai,
  LAYER.DenChieuSang,
  LAYER.DenGiaoThong,
  LAYER.DongHoKhachHang,
  LAYER.DiemCuoiOng,
  LAYER.DiemNut,
  LAYER.DongHoTong,
  LAYER.GiaoThong,
  LAYER.Gieng,
  LAYER.HoGa,
  LAYER.HostDieuKhien,
  LAYER.KhuVucNgap,
  LAYER.KhuVucXuLyRacThai,
  LAYER.LuuVucThoatNuoc,
  LAYER.MiengXa,
  LAYER.MoiNoiThoatNuoc,
  LAYER.NghiaTrang,
  LAYER.NguonGayONhiem,
  LAYER.NhaMayDien,
  LAYER.NhaMayNuoc,
  LAYER.NutCongSuat,
  LAYER.PhuTai,
  LAYER.SuDungDat,
  LAYER.CapTruyenDan,
  LAYER.DayChieuSang,
  LAYER.ThietBiDien,
  LAYER.TimDuong,
  LAYER.TramBienAp,
  LAYER.TramBom,
  LAYER.TramVienThong,
  LAYER.TramXuLyNuocThai,
  LAYER.TramTrungChuyenCTR,
  LAYER.TuyenOngCapNuoc,
  LAYER.Van,
  LAYER.ViTriLayNuoc,
  LAYER.ViTriDauNoiVoiTuyenOngDan,
  ],
  [APPLICATION.QuanLyHaTangKyThuat]: [LAYER.BASE_MAP,
  LAYER.BaoVeMoiTruong,
  LAYER.BeChua,
  LAYER.BuuCuc,
  LAYER.CayXanh,
  LAYER.CongThoatNuoc,
  LAYER.CongVien,
  LAYER.CotDien,
  LAYER.CongTrinhCaoTang,
  LAYER.CongTrinhNgam,
  LAYER.CongTrinhXayDung,
  LAYER.DuongDayTruyenTai,
  LAYER.DenChieuSang,
  LAYER.DenGiaoThong,
  LAYER.DongHoKhachHang,
  LAYER.DiemCuoiOng,
  LAYER.DiemNut,
  LAYER.DongHoTong,
  LAYER.GiaoThong,
  LAYER.Gieng,
  LAYER.HoGa,
  LAYER.HostDieuKhien,
  LAYER.KhuVucNgap,
  LAYER.KhuVucXuLyRacThai,
  LAYER.LuuVucThoatNuoc,
  LAYER.MiengXa,
  LAYER.MoiNoiThoatNuoc,
  LAYER.NghiaTrang,
  LAYER.NguonGayONhiem,
  LAYER.NhaMayDien,
  LAYER.NhaMayNuoc,
  LAYER.NutCongSuat,
  LAYER.PhuTai,
  LAYER.SuDungDat,
  LAYER.CapTruyenDan,
  LAYER.DayChieuSang,
  LAYER.ThietBiDien,
  LAYER.TimDuong,
  LAYER.TramBienAp,
  LAYER.TramBom,
  LAYER.TramVienThong,
  LAYER.TramXuLyNuocThai,
  LAYER.TramTrungChuyenCTR,
  LAYER.TuyenOngCapNuoc,
  LAYER.Van,
  LAYER.ViTriLayNuoc,
  LAYER.ViTriDauNoiVoiTuyenOngDan
  ],
  [APPLICATION.QuanLySuCo]: [LAYER.BASE_MAP, LAYER.HienTrang, LAYER.DIEM_SU_CO],
  [APPLICATION.QuanLySuCoDonVi]: [LAYER.BASE_MAP, LAYER.HienTrang, LAYER.DIEM_SU_CO],
  [APPLICATION.TiepNhanSuCo]: [LAYER.DIEM_SU_CO, LAYER.BASE_MAP]
};

export const FIELDS_NO_EDIT = [
  'MaPhuongXa',
  'SHAPE_Length',
  'MaHuyenTP',
  'MaXa',
  'OBJECTID',
  'MaDMA',
  'GlobalID',
  'DoiQuanLy',
  'TGPhanAnh',
  'created_user',
  'created_date',
  'last_edited_user',
  'last_edited_date'
];